# Config file for automatic testing at travis-ci.org

language: python
dist: "xenial"
python:
  - 3.12
  - 3.13

cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"

stages:
  - lint
  - test
  - docs
  - name: deploy
    if: tag IS present

before_install:
  - pip install --upgrade pip
install:
  - pip install uv
  - pip install tox-travis
script:
  - tox

jobs:
  include:
    - stage: lint
      python: 3.13
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files
    - stage: docs
      python: 3.13
      install:
        - pip install uv
        - uv sync --dev
      script:
        - echo $PWD
        - sphinx-build -nWT -b dummy ./docs ./docs/_build
    - stage: deploy
      script:
        - echo Deploying to PyPI...
      before_deploy:
        # User and password environment variables are set as hidden variables through
        # the web interface in the project settings.
        - pip install --upgrade pip
        - pip install build twine
      deploy:
        provider: script
        script: python -m build && python -m twine upload dist/*
        skip_cleanup: true
        on:
          branch: master
          tags: true
